global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'nextjs'
    metrics_path: '/api/metrics'
    static_configs:
      - targets: ['main-server:3000']

  - job_name: 'ipfs-nodes'
    metrics_path: '/debug/metrics/prometheus'
    static_configs:
      - targets: 
        - 'storage-node-1:5001'
        - 'storage-node-2:5001'
        - 'storage-node-3:5001'
        - 'storage-node-4:5001'
    scrape_interval: 10s
    

